CREATE DATABASE IF NOT EXISTS TRANSACTIONS_DB;

USE TRANSACTIONS_DB;

CREATE USER IF NOT EXISTS 'stepik'@'%' IDENTIFIED BY '12345';

GRANT ALL PRIVILEGES ON TRANSACTIONS_DB.* TO 'stepik'@'%';

FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS transactions (
    idTransactions INT AUTO_INCREMENT PRIMARY KEY,
    sum DOUBLE,
    description VARCHAR(255),
    dateTime DATETIME,
    typeOfTransaction INT
);